import type { State } from '../domain/types.js';
const edges: Partial<Record<State, State[]>> = {
  RECEIVED: ['DISCOVERY'], DISCOVERY: ['EVIDENCE_READY', 'NEED_MORE_EVIDENCE'], EVIDENCE_READY: ['ATTRIBUTION'],
  ATTRIBUTION: ['DUPLICATE_CHECK', 'NEED_MORE_EVIDENCE'], DUPLICATE_CHECK: ['IMPACT_ESTIMATION', 'PROPOSAL_READY', 'NEED_MORE_EVIDENCE', 'COMPLETED'],
  IMPACT_ESTIMATION: ['PROPOSAL_READY', 'NEED_MORE_EVIDENCE'], PROPOSAL_READY: ['POLICY_CHECK', 'DISCOVERY'],
  POLICY_CHECK: ['WAITING_APPROVAL', 'EXECUTING'], WAITING_APPROVAL: ['EXECUTING', 'PROPOSAL_READY', 'DISCOVERY'],
  EXECUTING: ['VERIFYING'], VERIFYING: ['COMPLETED'], NEED_MORE_EVIDENCE: ['DISCOVERY'], RECOVERABLE: ['DISCOVERY', 'EXECUTING', 'VERIFYING', 'IMPACT_ESTIMATION', 'PROPOSAL_READY', 'POLICY_CHECK', 'DUPLICATE_CHECK', 'ATTRIBUTION', 'EVIDENCE_READY', 'WAITING_APPROVAL', 'RECEIVED']
};
export function canTransition(from: State, to: State) { return from !== 'COMPLETED' && from !== 'FAILED' && (to === 'RECOVERABLE' || to === 'FAILED' || edges[from]?.includes(to) === true); }
